### ISSUE TITLE
wasm-mutate: Invalid wasm module produced

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasm-tools#388]
Sorry I keep opening bugs with the same title, I dunno how to open a better title for fuzz-bugs...

In any case this input:

```wasm
(module
  (type (;0;) (func (result i32)))
  (func (;0;) (type 0) (result i32)
    i32.const -14671840
    i64.extend_i32_u
    i32.const -1
    i64.extend_i32_u
    i64.rem_s
    i64.const -1
    i64.le_u)
  (data (;0;) ""))
```

will yield:

```
$ cargo run --bin wasm-mutate -- --seed 11494877297919394047 ./test.wasm -o wat.wasm --preserve-semantics
$ cargo run --bin wasm-validate-rs wat.wasm 
Error: type mismatch: expected i64, found i32 (at offset 36)
```

cc @Jacarte, and note that I tested this with https://github.com/bytecodealliance/wasm-tools/pull/387 and the issue still reproduces, so I think that this is separate from that.

**Comment by alexcrichton** [comment]
Oh I should note that the produced wasm is:

```wasm
(module
  (type (;0;) (func (result i32)))
  (func (;0;) (type 0) (result i32)
    i32.const -14671840
    i64.extend_i32_u
    i32.const -1
    i64.extend_i32_u
    i64.rem_s
    i32.const -1
    i64.le_u
    i32.const 0
    i32.shl)
  (data (;0;) ""))
```

**Comment by Jacarte** [comment]
I see, thanks @alexcrichton

**Comment by fitzgen** [comment]
Fixed in #387  I think?

**Comment by alexcrichton** [comment]
Ah unfortunately no, I tested with that but it didn't seem to fix this. I think the bug is that this:

```wasm
    i64.const -1
    i64.le_u
```

is changed to:

```wasm
    i32.const -1
    i64.le_u
```

**Comment by Jacarte** [comment]
Well, overall, the type propagation algorithm is not working :(. It would be better to separate the `equivalence` classes by type during Wasm 2 egg translation. We will solve this by separating the operators in the egraph by type, for example, instead of having `(add ?x ?y)`, we will have `(i32add ?x ?y)`. 

The egraph will be increased by the number of types in Wasm, but, so far, we have not observed that this will be an overhead problem.

**Comment by Jacarte** [comment]
I think this can be closed :)

**Comment by alexcrichton** [comment]
🎊
